name = "SHA"
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"
authors = ["Elliot Saba <staticfloat@gmail.com>"]
version = "0.7.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "â‰¥ 1.0.0"
